GET http://localhost:8000/students

###

GET http://localhost:8000/students/69b2299d8e94edfbadaa25e4

###

POST http://localhost:8000/students
Content-Type: application/json  

{
    "name": "Postman Test",
    "grade": "12"
}

###

DELETE http://localhost:8000/students/69b363a45518254529b48886

###

PATCH  http://localhost:8000/students/69b2299d8e94edfbadaa25e4
Content-Type: application/json  

{
    "name": "Yoshi Biesboer",
    "grade": "12"
}